server:
  port: 8761
  shutdown: graceful

spring:
  application:
    name: discovery-server
  lifecycle:
    timeout-per-shutdown-phase: 10s

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
